---
# config.yml
#    
#    ██╗░░██╗██╗██╗░░░░░██╗░░░░░██████╗░███████╗░█████╗░████████╗██╗░░██╗░██████╗░█████╗░██╗░░░██╗███╗░░██╗██████╗░
#    ██║░██╔╝██║██║░░░░░██║░░░░░██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██║░░██║██╔════╝██╔══██╗██║░░░██║████╗░██║██╔══██╗
#    █████═╝░██║██║░░░░░██║░░░░░██║░░██║█████╗░░███████║░░░██║░░░███████║╚█████╗░██║░░██║██║░░░██║██╔██╗██║██║░░██║
#    ██╔═██╗░██║██║░░░░░██║░░░░░██║░░██║██╔══╝░░██╔══██║░░░██║░░░██╔══██║░╚═══██╗██║░░██║██║░░░██║██║╚████║██║░░██║
#    ██║░╚██╗██║███████╗███████╗██████╔╝███████╗██║░░██║░░░██║░░░██║░░██║██████╔╝╚█████╔╝╚██████╔╝██║░╚███║██████╔╝
#    ╚═╝░░╚═╝╚═╝╚══════╝╚══════╝╚═════╝░╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝╚═════╝░░╚════╝░░╚═════╝░╚═╝░░╚══╝╚═════╝░
#
# You can see the list of sound effects at this link: "https://www.digminecraft.com/lists/sound_list_pe.php"
# Don't Change It!
config-version: 3.0.2
# Player Death
death:
  addsound: true
  blood: true
  blood-all-entity: true # Add Blood Particle to all entity hit, arching
  sound: # Sound name
  - "random.explode"
  volume: 1 # Volume sounds
  pitch: 1 # Pitch sounds

# Player Kills
kill:
  addsound: true
  blood: true
  blood-all-entity: true # Add Blood Particle to all entity hit, arching
  sound: # Sound name
  - "random.levelup"
  - "random.totem"
  volume: 1 # Volume sounds
  pitch: 1 # Pitch sounds
  particle: # Particle death
  
# Player Hit & Archery
hit:
  addsound: true
  blood: true
  blood-all-entity: true # Add Blood Particle to all entity hit, arching
  blood-to-attacker: false # Add Blood Particle to attacker
  sound: # Sound name
  - "random.orb"
  volume: 1 # Volume sounds
  pitch: 1 # Pitch sounds
...
